### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by Orangejewce92** [DenisD3D/Mc2Discord#88]
im getting version updates in console for a higher version than listed on CF. is the 1.19.3 version okay for 1.19.2?
 Forge

**Comment by DenisD3D** [comment]
Yes 1.19.3 version should be working on 1.19.2. I will update on curseforge
Thanks for reporting and please reopen if you encounter any issues

**Comment by Orangejewce92** [comment]
Version 4.0.2 does not work for 1.19.2 
Bot never turned on. 
Reverting to 3.3.0 worked 


Troubleshooting:
I did not gen a new config (never had to before) is there something new with the 4.0 series bots?

**Comment by Orangejewce92** [comment]
Tried testing again with new config and bot will not connect
again this is on forge 1.19.2

**Comment by Orangejewce92** [comment]
i've used your /mc2discord invite command to insure i got the correct permissions.
I reset my bot token to ensure that wasnt the issue either. still not connecting.
when i use /mc2discord status it says error

**Comment by Orangejewce92** [comment]
[http://m2d.denisd3d.fr/uploads/view?key=207e5c17-4763-45b6-80fc-e84f15d40a95](url)

**Comment by Orangejewce92** [comment]
Dev found issue: message intent in dev portal was off. thanks again!
